GET http://localhost:3000/users

###

POST http://localhost:3000/users
Content-Type: application/json

{
"firstname":"Shivansh",
"lastname":"Hedaoo"
}

###

PATCH http://localhost:3000/users/5f66f9bb7773533b04ab1613
Content-Type: application/json

{
"firstname":"Michael"
}

###

DELETE http://localhost:3000/users/5f66f9bb7773533b04ab1613

###

PUT http://localhost:3000/users/5f66f9bb7773533b04ab1613
Content-Type: application/json

{
"firstname":"Put test",
"lastname": "just Changed"
}